### ISSUE TITLE
Bug: Map Localized labels language code

### ISSUE THREAD

**Issue by daggen** [iggsn/XTBPlugin.SystemComparerer#11]
Hi,

I've a multi language setup. When I use your tool to check my environments it doesn't match the localizedLabels with correct language. Hence it states that they are not matching. It is correct that it is different order but the tool should try to do match if there exist any. See pictures. Thanks for a great tool!
![image](https://user-images.githubusercontent.com/1481424/67469141-10202400-f64c-11e9-920d-98f045d346b7.png)
![image](https://user-images.githubusercontent.com/1481424/67469240-30e87980-f64c-11e9-8331-bf06694e8626.png)

**Comment by iggsn** [comment]
This has been incormporated in verion 1.2019.1.19
