### ISSUE TITLE
Suggested new feature for XRMToolbox users

### ISSUE THREAD

**Issue by eccountable** [iggsn/XTBPlugin.SystemComparerer#13]
1. Have a way to filter out all objects that are the same so that we can only focus on the items that are changed.

2. Export to Excel

**Comment by iggsn** [comment]
Hi @eccountable 
hiding equal objects is a nice idea and was requested already. I am working on it. During testing I saw, that I have some false positives. As soon as this is fixed, I will release it.

Export to Excel I have to check. This would be a bigger feature. But hiding is nearly implemented.

Kind regards,
Lars

**Comment by iggsn** [comment]
Created new #14 to include the filter option.
Excel will maybe happen later, but is deferred for now.
Focus on changed items is possible with version 1.2019.1.26.

Have fun.
