### ISSUE TITLE
Filtering and False differences

### ISSUE THREAD

**Issue by simes1** [iggsn/XTBPlugin.SystemComparerer#7]
Thank you I've found this tool generally really useful but there's a couple of things I've found problematic:

1. **"False" Differences:** Sometimes I find I have two lists which are functionally identical but, for whatever reason, presented in a different order.  I have the same problem exporting solutions, unpacking and comparing the unpacked XML files in Visual Studio.  See attached screenshot of a compare immediately after a sandbox full copy (and which should therefore be identical)

![false difference 9700_10051](https://user-images.githubusercontent.com/11423243/44983159-2367c000-af70-11e8-8a5a-2b3ac364a42f.PNG)
![false difference 10051_4200](https://user-images.githubusercontent.com/11423243/44983160-2367c000-af70-11e8-81cc-04fbbd654c93.PNG)

2. **Lack of Filtering:**  It would be good to be able to exclude known/understood differences with some sort of filtering.  Options might include by entity, by solution, custom/OotB or just clicking to exclude individual things like in 1. above.

Simon

**Comment by iggsn** [comment]
Hi Simon,
thank you for the detailed explanation. I will take that in consideration.
Already saw, that there is some issue in the comparisson. Will work on that soon and release a fix, if done.

-Lars

**Comment by iggsn** [comment]
Hi Simon,
I just released a new version (1.2018.12.2). It might take a moment to get published via XrmToolBox store.
If you want you can pull it directly through the NuGet download. I hope I fixed the comparison issue inside the Optionsets. It compares by value as it should. Also the UI has little bit improved.

I leave this open since you had 2 requests :-)

-Lars

**Comment by simes1** [comment]
Sorry Lars I had notifications set to an old email address so I missed this.  So far the updated version appears to throw up viewer false differences.  I can't unfortunately get the new views and forms differences to work even when the source and target are the same.  I'll post an new issue for this when I get a moment

**Comment by iggsn** [comment]
Hi Simon,
I guess the false differences are gone for the OptionSets etc? The forms and views are really in an early stage yet and need lot of improvements.

**Comment by simes1** [comment]
Yes I think so.  I see fewer false differences now - lists of one sort or another (but where the order of the list didn't actually matter) were the source of the vast majority of these.

**Comment by iggsn** [comment]
I rate this as closed. The filtering will be solved as part of #8
