### ISSUE TITLE
Filtering to get rid of false positive

### ISSUE THREAD

**Issue by Paulus999** [iggsn/XTBPlugin.SystemComparerer#8]
Fantastic Tool
Could you include a mechanism to ignore specific parts of the metadata.

e.g. I am comparing 2 instances and virtually every attribute on custom entities (and some system ones) is giving me a difference because the Column Number of the attribute is different. If this was ignored for comparison purposes then it would allow me to concentrate on where the actual differences were.

many thanks

**Comment by iggsn** [comment]
Hi Paulus999,

thank you. It is more a revival of an old tool :-)
I marked it as enhancement. But cannot commit on a fast implementation.

-Lars

**Comment by MscrmTools** [comment]
That is a must have feature to implement. Especially when comparing from a source org where everything is unmanaged to a target org where everything is (should be :)) managed.
Currently, IsManaged is different for almost all components

**Comment by iggsn** [comment]
Hi @MscrmTools,

thank your for the Input. That is an important thing with the isManaged. This will come as an option with the next release.

**Comment by MscrmTools** [comment]
Great! Thanks

**Comment by iggsn** [comment]
Hi @MscrmTools and @Paulus999,

sometimes things take longer. Have fun with the new release 1.2019.1.26 which should be available tomorrow in the store.
It includes some fixes, but it now also ignores "IsManaged" and "CanBeChanged" by Settings, Sorts the Poperties by Name and many more.

#14 

Have fun
